version: '3.1'

services:
  pgdb:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  app:
    image: 'finmid_app'
    build:
      context: .
    container_name: finmid_app
    depends_on:
      - pgdb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/db
