server:
  servlet:
    context-path: /v1

spring:
  datasource:
    hikari:
      schema: public
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


