### create account
POST {{host}}/v1/account
Content-Type: application/json

{
  "balance": "142.42"
}

### reauest for not existed account
GET {{host}}/v1/account/111110
Content-Type: application/json

### reauest for exist account
GET {{host}}/v1/account/2
Content-Type: application/json